version: "3.9"

services:
  postgres:
    image: postgres:16
    env-file:
      - deploy/.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "mlflow,mlflow:5000,localhost:*"
      # MLFLOW_SERVER_CORS_ALLOWED_ORIGINS: "http://localhost:5000"
    command:
      [
        "server",
        "--backend-store-uri",
        "postgresql://mlflow:mlflow@postgres:5432/mlflow",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--default-artifact-root",
        "/shared/artifacts",
      ]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - mlflow_artifacts:/shared/artifacts

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.app
    command: ["python", "-m", "apps.smoke_run"]
    env-file:
      - deploy/.env.docker
    depends_on:
      mlflow:
        condition: service_started
    volumes:
      - mlflow_artifacts:/shared/artifacts

volumes:
  postgres_data:
  mlflow_artifacts:
